### ISSUE TITLE
Feature Request: Increase the maximum distance. 

### ISSUE THREAD

**Issue by n8bar** [Vl4dimyr/TombstoneHelper#1]
I'd really like to be able to nab my gear from 2 rooms away in the sunken crypts. Elite Draugr Archers spawn in and won't let me have my stuff. It's probly a bit cheaty but it will reduce rage quits.

**Comment by Vl4dimyr** [comment]
Hey, as long as it still feels cheaty it's fine xD, but this was only one of the two reasons why I did set a maximum range.
I will take a look at the actual maximum range in which I can detect the tombstone. Since I'm using a collider to find the damn thing, I need to make sure it doesn't affect performance when the range is increased. I will at least add some kind of warning in case it does impact performance. I'll see when I can find time to test/change this. First step: install Valheim xD

**Comment by Vl4dimyr** [comment]
The new maximum is now 100 (https://github.com/Vl4dimyr/TombstoneHelper/commit/5d694647760daaeda7b586c029fe7c69b6a33794).

I've tested and found that the tombstone will be found as long as it is rendered (around 200).
Interacting starts to run into issues much earlier, so even around 100 the game does not recognize the tombstone owner and cancels the interaction. I stepped just a few meters closer and the interaction worked. But even that seemed inconsistent depending on the amount of object in between.

I decided to set the maximum to 100 as it worked most of the time, and getting a few steps closer to fix the owner check issue isn't a big deal.

Have fun and hopefully less rage-quits!
